create table employment_logs
(
    employment_log_id              number generated by default as identity primary key,
    first_name                     varchar2(20),
    last_name                      varchar2(20),
    employment_action              varchar2(10),
    employment_status_updtd_tmstmp timestamp(0) WITH TIME ZONE,
    constraint ck_emp_logs_action check ( employment_action in ('HIRED', 'FIRED'))
)