create table projects
(
    projectId           number generated by default as identity primary key,
    project_description varchar2(100),
    project_investments number(7, -3),
    project_revenue     number(7, 2),
    constraint ck_projects_desc check ( length(project_description) > 10 ),
    constraint ck_projects_invest check ( project_investments >= 500 )
)