insert into PROJECTS (PROJECT_DESCRIPTION, PROJECT_INVESTMENTS, PROJECT_REVENUE)
values ('it super project', 500, 2000);

insert into PROJECTS (PROJECT_DESCRIPTION, PROJECT_INVESTMENTS, PROJECT_REVENUE)
values ('design super project', 2499, 1800);